### ISSUE TITLE
Unit test test_imageSet.py : test_compute_zline_distance fails 

### ISSUE THREAD

**Issue by massyah** [cbib/dypfish#3]
It seems that an image set is missing : 

```
.
======================================================================
ERROR: test_compute_zline_distance (src.tests.test_imageSet.TestImageSet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hayssam/Documents/dypfish/src/tests/test_imageSet.py", line 183, in test_compute_zline_distance
    image_set = ImageSet(self.repo, path_list=['mrna/actn2/immature/'])
  File "/Users/hayssam/Documents/dypfish/src/image_set.py", line 29, in __init__
    raise LookupError("Cannot init ImageSet, path %s is absent from repository" % p)
LookupError: Cannot init ImageSet, path mrna/actn2/immature/ is absent from repository

----------------------------------------------------------------------
Ran 82 tests in 129.389s
```

**Comment by tigloo123** [comment]
All unit test have to use the example_hdf5 file

**Comment by massyah** [comment]
cf https://github.com/cbib/dypfish/blob/eb78c757d726fcf5fa0115596a17b30e847f4976/src/tests/test_imageSet.py#L182-L185

**Comment by bdartigues** [comment]
H5 test data now contains a set of muscle images to run the test
