### ISSUE TITLE
mtoc_periph_analysis.py give error

### ISSUE THREAD

**Issue by EdgarLefevre** [cbib/dypfish#39]
When I ran mtoc_periph_analysis.py I got this error : 

```
Traceback (most recent call last):
  File "src/analysis/mtoc/mtoc_periph_analysis.py", line 95, in <module>
    plot.compute_violin_plot_ratio(mRNA_df, 'mrna')
  File "/home/edgar/Documents/dypfish/src/plot.py", line 309, in compute_violin_plot_ratio
    sns_violinplot(dd, my_pal, tgt_fp, x=groupby[0], no_legend=False, rotation=45)
  File "/home/edgar/Documents/dypfish/src/plot.py", line 108, in sns_violinplot
    fig.savefig(figname, format='png')
  File "/home/edgar/anaconda3/envs/test_dypfish/lib/python3.7/site-packages/matplotlib/figure.py", line 2062, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/edgar/anaconda3/envs/test_dypfish/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "/home/edgar/anaconda3/envs/test_dypfish/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    with cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/home/edgar/anaconda3/envs/test_dypfish/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/edgar/anaconda3/envs/test_dypfish/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 626, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/home/edgar/anaconda3/envs/test_dypfish/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 597, in to_filehandle
    flag=flag, return_opened=return_opened, encoding=encoding)
  File "/home/edgar/anaconda3/envs/test_dypfish/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 611, in to_filehandle
    fh = io.open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/edgar/Documents/dypfish/src/analysis/mtoc/output_peripheral/mrna_original_ratio_plot.png'
```

**Comment by EdgarLefevre** [comment]
Patched and tested
