### ISSUE TITLE
degree_of_clustering.py

### ISSUE THREAD

**Issue by EdgarLefevre** [cbib/dypfish#40]
Running degree_of_clustering.py gave me : 

```
/home/edgar/Documents/dypfish/src/plot.py:10: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "src/analysis/degree_of_clustering/degree_of_clustering.py", line 8, in <module>
    import plot
  File "/home/edgar/Documents/dypfish/src/plot.py", line 6, in <module>
    from helpers import create_dir_if_needed_for_filepath
  File "/home/edgar/Documents/dypfish/src/helpers.py", line 9, in <module>
    from colormap import rgb2hex
  File "/home/edgar/anaconda3/envs/test_dypfish/lib/python3.7/site-packages/colormap/__init__.py", line 36, in <module>
    colormap_names = c.colormaps + c.diverging_black
  File "/home/edgar/anaconda3/envs/test_dypfish/lib/python3.7/site-packages/colormap/colors.py", line 718, in _get_colormap_mpl
    from matplotlib.pyplot import colormaps as _cmaps
  File "/home/edgar/anaconda3/envs/test_dypfish/lib/python3.7/site-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/home/edgar/anaconda3/envs/test_dypfish/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 17, in <module>
    line for line in traceback.format_stack()


  matplotlib.use("Agg")
Traceback (most recent call last):
  File "src/analysis/degree_of_clustering/degree_of_clustering.py", line 14, in <module>
    from image_set import ImageSet
  File "/home/edgar/Documents/dypfish/src/image_set.py", line 14, in <module>
    from image import ImageWithSpots, ImageWithIntensities, ImageWithMTOC, \
  File "/home/edgar/Documents/dypfish/src/image.py", line 42, in <module>
    from constants import PERIPHERAL_INTENSITIES_PATH_SUFFIX
ImportError: cannot import name 'PERIPHERAL_INTENSITIES_PATH_SUFFIX' from 'constants' (/home/edgar/Documents/dypfish/src/constants.py)


```

**Comment by EdgarLefevre** [comment]
A new error just appears : 
```
Traceback (most recent call last):
  File "src/analysis/degree_of_clustering/degree_of_clustering.py", line 64, in <module>
    molecule_type="mrna")
  File "src/analysis/degree_of_clustering/degree_of_clustering.py", line 27, in compute_degree_of_clustering
    degree_of_clustering = np.array(image_set.compute_degree_of_clustering())
  File "/home/edgar/Documents/dypfish/src/image_set.py", line 231, in compute_degree_of_clustering
    return [image.compute_degree_of_clustering() for image in self.images]
  File "/home/edgar/Documents/dypfish/src/image_set.py", line 231, in <listcomp>
    return [image.compute_degree_of_clustering() for image in self.images]
  File "/home/edgar/Documents/dypfish/src/image.py", line 534, in compute_degree_of_clustering
    h_star = self.get_clustering_indices()
  File "/home/edgar/Documents/dypfish/src/helpers.py", line 28, in wrapper
    value = decorated_method(instance, *args, **kwargs)
  File "/home/edgar/Documents/dypfish/src/image.py", line 529, in get_clustering_indices
    return self.compute_clustering_indices()
  File "/home/edgar/Documents/dypfish/src/image.py", line 553, in compute_clustering_indices
    k = self.ripley_k_random_measure_2D(IF, my_lambda, nuw)
  File "/home/edgar/Documents/dypfish/src/image.py", line 572, in ripley_k_random_measure_2D
    P = signal.convolve(IF, IF_rev)
NameError: name 'signal' is not defined
```

**Comment by bdartigues** [comment]
PERIPHERAL_INTENSITIES_PATH_SUFFIX wa sin a code , need a pull to update:::: Need to import signal from scipy in image.py; done
